### PR TITLE
remove divide large requests with range

### PR DESCRIPTION
**Pull request by openmosix**
I'm up for letting this go. Thoughts?

@taganaka @andreacfm @tejo

### CODE REVIEW

**Comment by tejo** [comment]
:+1:

**Comment by andreacfm** [comment]
@tejo @openmosix @taganaka
Ranges does not looks very clear and friendly to me. I agree on checking something else.

**Comment by tejo** [comment]
for paginated results in general I’d like to use with something like

{
  "response": [{
    "id":    1,
    "name": "Delicious Food"
  }, {
    "id":   2,
    "name": "More Delicious Food"
  }],
  "count": 2,
  "pagination": {
    "previous": null,
    "next":     null,
    "current":  1,
    "per_page": 10,
    "count":    2,
    "pages":    1
  }
}

​

**Comment by andreacfm** [comment]
I think here we must find our way on multiple aspects:

* where do we display the pagination info? I see two schools here. Place the pagination info in the header or into the response payload. I personally prefer the payload solution (as @tejo example)

* once we define where to display the info we must define a payload. I will look for several examples and I will post here what I find. The one proposed by @tejo looks reasonable.

* what are the params that trigger the pagination? 
  * page, per_page
  * page, size
  * offset, limit

* what is the maximum amount of records we will allow in a single page?
  * 100
  * 1000

**Comment by openmosix** [comment]
Ok we are all on the same page of nuking this. I'll open an issue on how to handle pagination (in a standard way for all APIs).

**Pull request merged**
